# Семинар 1. Python, numpy

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


Несколько простеньких задачек, чтобы вспомнить Python.

![Песочница](https://image.freepik.com/free-vector/kids-playing-in-sandbox-cartoon-style_22350-463.jpg)

### list comprehensions

- Создайте лист с квадратами чисел от 1 до 10 двумя способами: простой цикл и list comprehensions

In [2]:
li = []
for i in range(1, 11):
    li.append(i**2)

In [3]:
li

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [4]:
li2 = [i**2 for i in range(1, 11)]
li2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

- С помощью list comprehensions создайте новый лист с квадратами только тех чисел от 1 до 10, что без остатка делятся на 3.

In [5]:
a = [i**2 for i in range(1, 11) if i % 3 == 0]

- С помощью list comprehensions замените все отрицательные значения в листе на 0

In [6]:
candy_prices = [35.4, 26.7, -33.8, 41.9, -100, 25]
prices = [i if i>0 else 0 for i in candy_prices]

- Объедините два листа. Оставьте только уникальные значения :)

In [8]:
cookies_prices = [31.7, 56.8, 112.3, 2.9]
set(candy_prices + cookies_prices)

{-100, -33.8, 2.9, 25, 26.7, 31.7, 35.4, 41.9, 56.8, 112.3}

### lambda function

- Написать двумя способами (с помощью def и с помощью lambda) функцию для подсчета квадрата числа $x$ :) Применить к диапазону от 1 до 10.

In [9]:
# variant1
def my_square(x):
    return x**2

In [10]:
my_square(4)

16

In [11]:
list(map(my_square, range(1,11)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [12]:
list(map(lambda x: x**2, range(1, 11)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

- отсортируйте айдишники по убыванию

In [13]:
ids = ['id1', 'id2', 'id30', 'id3','id100', 'id22']
sorted(ids, key=lambda x:int(x[2:]), reverse=True)

['id100', 'id30', 'id22', 'id3', 'id2', 'id1']

In [14]:
(lambda x: x[2:])('id100')

'100'

### Словари и еще немного листы 

- Вспомните, как создать словарь :)

In [15]:
dic = {1:'a', 2:'b', 3:'c'}
dic.items()

dict_items([(1, 'a'), (2, 'b'), (3, 'c')])

- Выведите по очереди записи из своего словаря (ключ, айтем)

In [16]:
for i in dic.keys():
    print(i, dic[i])

1 a
2 b
3 c


- Выведите по очереди элементы листа и их индексы

In [17]:
elems = [500, 100, 200, 600]
for ind, el in enumerate(elems):
    print(ind, el)

0 500
1 100
2 200
3 600


- Вспомните, как вывести последний элемент; все, кроме последнего; через один элемент, начиная с первого; в обратном порядке

In [18]:
elems[-1]

600

In [19]:
elems[:-1]

[500, 100, 200]

In [20]:
elems[::2]

[500, 200]

In [21]:
elems[::-1]

[600, 200, 100, 500]

### strings

- Получите лист с отдельными словами строки

In [22]:
s = "котятки, привет"
s.split(',')

['котятки', ' привет']

- Объедините в строку слова из листа. Не забудьте про пунктуацию :)

In [23]:
words = ["Привет", "котятки"]
', '.join(words)

'Привет, котятки'

https://regex101.com/ Тренажер для жаждущих поизучать регулярки

### files

- Создайте новый текстовый файл и запишите в него что-нибудь :)

In [24]:
file = open('my_file.txt', 'w')
file.write('Привет всем \n')
file.write('Всем хорошего дня')

file.close()

- Считайте файл по строкам

In [25]:
with open('my_file.txt') as f:
    for line in f:
        print(line)

Привет всем 

Всем хорошего дня


# numpy

In [26]:
import numpy as np

In [27]:
np.random.seed(10)

- Вспоминаем, как создавать матрицы из ноликов, едничек, диагональную, матрицу случайных величин :)

In [28]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [29]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.random.poisson(lam=5, size=(5,3))

array([[4, 3, 3],
       [8, 7, 5],
       [2, 7, 4],
       [7, 4, 3],
       [3, 4, 6]])

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

- Записать все значения матрицы в один лист

In [33]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- Из двумерного массива отберите в один лист элементы с индексами (0,0), (1,2), (2,2)

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a[[0, 1, 2], [0, 2, 2]]

array([1, 6, 9])

- Создайте таблицу умножения от 1 до 10

Перед тем как идти в бой :)

In [36]:
x = np.arange(4)
y = np.arange(5)

In [37]:
y

array([0, 1, 2, 3, 4])

In [38]:
y1 = y[:, None]
y1.shape

(5, 1)

In [39]:
y[:, np.newaxis] #тот же y1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [40]:
b = x * y1
b.shape

(5, 4)

In [41]:
b

array([[ 0,  0,  0,  0],
       [ 0,  1,  2,  3],
       [ 0,  2,  4,  6],
       [ 0,  3,  6,  9],
       [ 0,  4,  8, 12]])

In [42]:
def mult_table(n):
    rng = np.arange(1, n+1)
    return rng * rng[:, None]

In [43]:
mult_table(10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

- Оставьте только те элементы вектора a, которых нет в b.

In [44]:
a = np.array([1,2,3,4,8])
b = np.array([5,6,7,8,5])


In [45]:
a[a!=b] #так не работает

array([1, 2, 3, 4, 8])

In [46]:
a[a not in b] #и так тоже

array([[1, 2, 3, 4, 8]])

In [47]:
np.setdiff1d(a, b) #а вот так работает :)

array([1, 2, 3, 4])

In [48]:
a = [1, 2, 3]
b = [1, a]
a in b

True

- Заменить нолики на единички

In [49]:
purr = np.array([1, 2, 6, 0, 0 , 7])
np.where(purr == 0, 1, purr)

array([1, 2, 6, 1, 1, 7])

- Сделайте one-hot encoding вектора. То есть создайте матрицу, в которой число колонок равно числу уникальных значений вектора, а число строк — длине вектора. Заполните ячейки матрицы единичками, если на данной позиции в векторе встретилась конкретная цифра.

In [50]:
b = np.random.randint(1, 3, size=5)
b

array([1, 1, 1, 1, 1])

In [51]:
vec2 = np.array([1, 2, 4, 5, 5, 4])

In [52]:
(vec2[:, None] == np.unique(vec2)).astype(int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

- Найдите максимум в каждой строчке матрицы

In [53]:
np.random.seed(100)
a = np.random.normal(loc=3, scale=4, size=(4,4))
a.max(axis=1)

array([7.61214321, 6.92528315, 4.74065395, 6.26738829])

-  Выведите вектор отношения минимума к максимум для каждой строчки матрицы

In [54]:
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([-0.52535295, -0.18485502,  0.24635674,  0.1062037 ])

In [55]:
a.min(axis=1)/a.max(axis=1)

array([-0.52535295, -0.18485502,  0.24635674,  0.1062037 ])

- Уберите все пропущенные значения из vec

In [56]:
vec = np.array([1, 2, 3, np.nan, np.nan, 3])
vec[vec==vec]

array([1., 2., 3., 3.])

In [57]:
vec[~np.isnan(vec)]

array([1., 2., 3., 3.])

- Поменяйте первую и вторую колонку местами

In [58]:
arr = np.arange(9).reshape(3,3)
arr_new = arr[:, [1,0,2]]

- Найдите наиболее близкое значение вектора к заданному (по абсолютному значению)

In [59]:
def find_nearest(array, val):
    dif = np.abs(array - val)
    ind_min = dif.argmin()
    return array[ind_min]

In [60]:
a = np.array([1, 2, 7.84, 7.85])
value = 10
find_nearest(a, value)

7.85

- Посчитайте произведение всех элементов на диагонале матрицы

In [63]:
def diag_prod(x):
    return np.prod(np.diag(x))

In [64]:
x = np.ones((10,10))
diag_prod(x)

1.0

### Про картинки

![alt text](image1.png "Картинка")

В картинке 4 полосочки с пикселями :) Каждая полосочка содержит пять пикселей. Каждый пиксель содержит три бита (red, green, blue).

Такое изображение обычно хранится в виде трехмерного массива размерности $height \times width \times numChannels$, где число каналов часто равно 3 (или 4 в случае RGBA). Элементами такого массива являются 8-битовые натуральные числа (то есть возможные значения от 0 до 2^8-1 :) Чиселки влияют на насыщенность цвета — от черного (0) до максимально насыщенного (255).

- Нарисовать RGB картинку с помощью numpy :) Например, розовый квадратик

In [ ]:
# code

#### Для тех, кто не понял или хочет деталей

- [Броадксатинг](https://numpy.org/devdocs/user/theory.broadcasting.html)
- [Индексация](https://numpy.org/doc/stable/reference/arrays.indexing.html)